#server中都是对服务中间件的配置
#server:
#  port: 8085
#  servlet:#    context-path: /shop
#自定义属性，可以在代码中引用回来

#spring:#  freemarker:#    cache: false
#    template-loader-path:#    - classpath:/templates/
#    charset: UTF-8
#    content-type: text/html; charset=utf-8
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .ftlh
#  thymeleaf:#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:#      content-type: text/html; charset=utf-8

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  datasource:                                           # 数据源的相关配置
      type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
      url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: password
      hikari:
        connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
        minimum-idle: 5                 # 最小连接数
        maximum-pool-size: 20           # 最大连接数
        auto-commit: true               # 自动提交
        idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
        pool-name: DateSourceHikariCP     # 连接池名字
        max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
        connection-test-query: SELECT 1  redis:    host: 120.25.251.131
    port: 6379
    password: 123456
    database: 1
    timeout: 5000
    jedis:      pool:        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
  session:
    store-type: none
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: net.seehope.foodie.pojo          # 所有POJO类所在包路径 给所有pojo起了别名，使用的时候大小写都可以调用该类
  mapper-locations: classpath*:mappers/**/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
net:
  seehope:
    qq:
      appid: 123456789
      appsecret: 852852
    browser:
      baseStaticServerUrl: http://127.0.0.1:8848
    